### PR TITLE
fix issue with user_compset option

### LINKED ISSUE #396: user_compset broken
With cesm1_5_alpha06c, with cime at the current master:

```
[yslogin3:/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/scripts]$ ./create_newcase -user_compset 2000_DATM%QIA_CLM50%SP_SICE_SOCN_RTM_SGLC_SWAV -user_pes_setby clm -res f10_f10 -mach yellowstone -case testcase_0318b
Setting configuration directory to /glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/scripts
ERROR create_newcase: no compset match was found in any of the following files:/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/cime_config/cesm/allactive/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/driver_cpl/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cam/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cism/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/clm/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cice/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/pop/cime_config/config_compsets.xml
Uncaught exception from user code:
    ERROR create_newcase: no compset match was found in any of the following files:/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/cime_config/cesm/allactive/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/driver_cpl/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cam/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cism/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/clm/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/cice/cime_config/config_compsets.xml
/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/components/pop/cime_config/config_compsets.xml
 at /glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/utils/perl5lib/Config/ConfigCompsetGrid.pm line 115
    ConfigCompsetGrid::getCompsetLongname('/glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/...', '2000_DATM%QIA_CLM50%SP_SICE_SOCN_RTM_SGLC_SWAV', 'ConfigCase=HASH(0x1fa0270)') called at ./create_newcase line 296
```

This works if I use a compset for which there is an alias defined (changing CLM50 to CLM45 in this case). But it appears that the user_compset functionality doesn't work for compsets where the alias is not defined anywhere.

### PR DESCRIPTION
**Pull request by jedwards4b**
The original problem was that user compsets that matched compsets with aliases would not pick up the user mods associated with that alias.   The original fix failed to handle user_compsets that did not have an associated alias.  This fix first searches for a matching alias and then
falls back to the old user_compset method.   

Test suite: yellowstone preaplha intel drv
Test baseline: cesm1_5_alpha06d
Test namelist changes: none
Test status: bit for bit

Fixes: #396

Code review:

### CODE REVIEW

File: utils/perl5lib/Config/ConfigCompsetGrid.pm [hunk 1]
```diff
@@ -112,12 +112,12 @@ sub getCompsetLongname
 	    $file =~ s/\$MODEL/$model/;
 	    $outstr .= "$file\n";
 	}
-	$logger->logdie ($outstr);
+	$logger->logwarn ($outstr);
```
Comment (billsacks) [inline utils/perl5lib/Config/ConfigCompsetGrid.pm]: Changing this from an error to a warning does not feel like a robust fix to me. I see two problems with this:

(1) If this is called for a case that uses -compset (rather than -user_compset), then this should generate an error, not a warning. Otherwise you end up with a cryptic death if you try to create a case with a non-existent compset:

```
Use of uninitialized value $pes_setby in concatenation (.) or string at
    ./create_newcase line 313 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you the
    name of the variable (if any) that was undefined. In some cases it cannot
    do this, so it also tells you what operation you used the undefined value
    in.  Note, however, that perl optimizes your program and the operation
    displayed in the warning may not necessarily appear literally in your
    program.  For example, "that $foo" is usually optimized into "that "
    . $foo, and the warning will refer to the concatenation (.) operator,
    even though there is no . in your program.

Use of uninitialized value $components in split at ./create_newcase line 328 (#1)
grid longname is : a%0.9x1.25_l%0.9x1.25_oi%gx1v6_r%r05_m%gx1v6_g%null_w%null
Uncaught exception from user code:
    ERROR create_newcase: config_file unset does not exist at ./create_newcase line 415.
 at ./create_newcase line 415
```

(2) If this is called when using -user_compset, then it should not even generate a warning - because the lack of existence of a compset match will be the usual, expected case. Many people wonder if they have done something wrong when they see a warning message, so we should not generate warning messages for the expected case.

Would it be possible to fix both of these problems by giving a new argument to getCompsetLongname, like "require_match"? require_match would be true if calling this with a case where -compset was provided, false for a case where -user_compset was provided. If require_match is true, then this generates an ERROR message. If false, this doesn't generate any message.

**Comment by billsacks** [comment]
Other than the one line note I made, this looks good to me. I compared the following:

(1)  case created with -compset:

./create_newcase -case stdcompset_0329 -compset IRCP85CLM45BGC -res f09_g16 -mach yellowstone

(2) Same case created with -user_compset:

 ./create_newcase -case user_compset_0329 -user_compset RCP8_DATM%QIA_CLM45%BGC_SICE_SOCN_RTM_SGLC_SWAV -res f09_g16 -mach yellowstone -user_pes_setby clm

(3) Slightly different case, for which there are no compset matches

./create_newcase -case user_compset_mod_0329 -user_compset RCP8_DATM%QIA_CLM50%BGC_SICE_SOCN_RTM_SGLC_SWAV -res f09_g16 -mach yellowstone -user_pes_setby clm

Differences were just as expected - so this looks good to me.

So this can be merged once the line note is resolved.

**Comment by jedwards4b** [comment]
Modified based on review.
